spring:
    controller:
        path-prefix: /api
    datasource:
        url: jdbc:p6spy:mysql://localhost:3306/HCNeed?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        batch:
            jdbc-url: jdbc:mysql://localhost:3306/HCNeed?useUnicode=true&characterEncoding=UTF-8
            driver-class-name: com.mysql.cj.jdbc.Driver
            username: root
            password: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

springdoc:
    api-docs:
        enabled: true
        path: /api-docs
    swagger-ui:
#        enabled: true
        disable-swagger-default-url: true
        configUrl: /v3/api-docs/swagger-config
        path: /swagger-ui.html
        url: ${springdoc.api-docs.path}
#    packages-to-scan: org.hcneed.server.controllers
