spring:
    controller:
        path-prefix: /api
    datasource:
        url: jdbc:p6spy:mysql://localhost:3306/HCNeed?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true